import { AmazonLogo, LinkedinLogo } from "@phosphor-icons/react";
import {
  siAmd,
  siAirbnb,
  siAlibabadotcom,
  siAliexpress,
  siAnaconda,
  siAnthropic,
  siApple,
  siAtlassian,
  siAutodesk,
  siBaidu,
  siBilibili,
  siBluesky,
  siBytedance,
  siCisco,
  siCloudflare,
  siCodeforces,
  siDeepseek,
  siDiscord,
  siDji,
  siDocker,
  siDouban,
  siDropbox,
  siEpicgames,
  siFacebook,
  siGhost,
  siGithub,
  siGitlab,
  siHuawei,
  siInstagram,
  siIntel,
  siLenovo,
  siLine,
  siKimi,
  siMinimax,
  siModelscope,
  siMastodon,
  siMedium,
  siMeta,
  siNetflix,
  siNotion,
  siNvidia,
  siPatreon,
  siPaypal,
  siPinterest,
  siPlaystation,
  siProton,
  siQq,
  siQwen,
  siReddit,
  siSamsung,
  siSap,
  siShopify,
  siSinaweibo,
  siSony,
  siSpotify,
  siSteam,
  siStripe,
  siTelegram,
  siTiktok,
  siTwitch,
  siUber,
  siUnity,
  siWhatsapp,
  siX,
  siXiaomi,
  siYoutube,
  siZoho,
  siZoom,
} from "simple-icons";
import { originalBrandMarks } from "./brandOriginalMarks.js";

function simpleBrand(icon, domains, options = {}) {
  return {
    id: options.id || icon.slug,
    label: options.label || icon.title,
    domains,
    simpleIcon: icon,
    background: options.background || "#fff",
    foreground:
      options.foreground ||
      (icon.hex.toLowerCase() === "ffffff" ? "#111" : `#${icon.hex}`),
  };
}

function phosphorBrand(id, label, domains, Icon, options = {}) {
  return {
    id,
    label,
    domains,
    Icon,
    iconWeight: options.iconWeight || "fill",
    background: options.background || "#fff",
    foreground: options.foreground || "#111",
  };
}

function originalBrand(id, label, domains, options = {}) {
  return {
    id,
    label,
    domains,
    originalMark: originalBrandMarks[id],
    background: options.background || "#fff",
    foreground: options.foreground || "#111",
  };
}

function textBrand(id, label, domains, letters, background, foreground = "#fff") {
  return { id, label, domains, letters, background, foreground };
}

export const brandRules = [
  simpleBrand(siGithub, ["github.com"]),
  originalBrand("google", "Google", ["google.com", "gmail.com"]),
  textBrand(
    "netease",
    "网易邮箱",
    ["163.com", "126.com", "yeah.net", "netease.com"],
    "易",
    "#d9271c",
  ),
  {
    id: "microsoft",
    label: "Microsoft",
    domains: [
      "microsoft.com",
      "outlook.com",
      "hotmail.com",
      "live.com",
      "windows.com",
      "office.com",
    ],
    mark: "microsoft",
    background: "#fff",
    foreground: "#737373",
  },
  textBrand(
    "nintendo",
    "Nintendo",
    ["nintendo.com", "nintendo.net"],
    "N",
    "#e60012",
  ),
  simpleBrand(siPlaystation, ["playstation.com"]),
  simpleBrand(siSony, ["sony.com"], { background: "#fff", foreground: "#111" }),
  originalBrand("openai", "OpenAI", ["openai.com"]),
  originalBrand("openrouter", "OpenRouter", ["openrouter.ai"]),
  originalBrand("zep", "Zep", ["getzep.com"]),
  simpleBrand(siGhost, ["ghost.io"]),
  originalBrand("figma", "Figma", ["figma.com"]),
  simpleBrand(siUnity, ["unity.com", "unity3d.com"], {
    background: "#fff",
    foreground: "#111",
  }),
  simpleBrand(siX, ["x.com", "twitter.com"]),
  simpleBrand(siQq, ["qq.com"], {
    id: "tencentqq",
    label: "腾讯 QQ",
    background: "#fff",
  }),
  simpleBrand(siXiaomi, ["xiaomi.com", "xiaomi.net", "mi.com"]),
  simpleBrand(siDocker, ["docker.com"]),
  simpleBrand(siAnaconda, ["anaconda.com"]),
  simpleBrand(siDeepseek, ["deepseek.com"]),
  simpleBrand(siKimi, ["kimi.com", "moonshot.cn"]),
  simpleBrand(siQwen, ["qwen.ai", "dashscope.aliyuncs.com"]),
  simpleBrand(siMinimax, ["minimax.io", "minimaxi.com"]),
  simpleBrand(siModelscope, ["modelscope.cn"]),
  simpleBrand(siBytedance, ["bytedance.com", "volcengine.com", "volces.com"]),
  originalBrand("zai", "Z.AI", ["z.ai", "zhipuai.cn", "bigmodel.cn"]),
  simpleBrand(siCodeforces, ["codeforces.com"]),

  simpleBrand(siApple, ["apple.com", "icloud.com", "me.com", "mac.com"]),
  phosphorBrand(
    "amazon",
    "Amazon",
    [
      "amazon.com",
      "amazon.co.uk",
      "amazon.de",
      "amazon.fr",
      "amazon.it",
      "amazon.es",
      "amazon.ca",
      "amazon.com.au",
      "amazon.co.jp",
      "amazon.in",
      "amazon.cn",
      "amazon.sg",
      "amazon.nl",
      "amazon.se",
      "amazon.pl",
      "amazon.ae",
      "amazon.sa",
      "amazon.com.br",
      "amazon.com.mx",
    ],
    AmazonLogo,
    { foreground: "#ff9900" },
  ),
  simpleBrand(siMeta, ["meta.com"]),
  simpleBrand(siFacebook, ["facebook.com", "facebookmail.com"]),
  simpleBrand(siInstagram, ["instagram.com"]),
  phosphorBrand("linkedin", "LinkedIn", ["linkedin.com"], LinkedinLogo, {
    foreground: "#0a66c2",
  }),
  originalBrand("slack", "Slack", ["slack.com"]),
  simpleBrand(siNotion, ["notion.com", "notion.so"]),
  simpleBrand(siAtlassian, ["atlassian.com"]),
  simpleBrand(siDropbox, ["dropbox.com"]),
  simpleBrand(siDiscord, ["discord.com"]),
  simpleBrand(siSpotify, ["spotify.com"]),
  simpleBrand(siNetflix, ["netflix.com"]),
  simpleBrand(siNvidia, ["nvidia.com"]),
  simpleBrand(siIntel, ["intel.com"]),
  simpleBrand(siAmd, ["amd.com"]),
  simpleBrand(siSamsung, ["samsung.com"]),
  simpleBrand(siPaypal, ["paypal.com"]),
  simpleBrand(siStripe, ["stripe.com"]),
  simpleBrand(siShopify, ["shopify.com"]),
  simpleBrand(siZoom, ["zoom.us", "zoom.com"]),
  simpleBrand(siCloudflare, ["cloudflare.com"]),
  simpleBrand(siGitlab, ["gitlab.com"]),
  simpleBrand(siReddit, ["reddit.com"]),
  simpleBrand(siSteam, ["steampowered.com", "steamgames.com"]),
  simpleBrand(siEpicgames, ["epicgames.com"]),
  simpleBrand(siAirbnb, ["airbnb.com"]),
  simpleBrand(siUber, ["uber.com"]),
  simpleBrand(siTiktok, ["tiktok.com"]),
  simpleBrand(siAlibabadotcom, ["alibaba.com", "alibabacloud.com"]),
  simpleBrand(siAliexpress, ["aliexpress.com"]),
  simpleBrand(siBaidu, ["baidu.com"]),
  simpleBrand(siHuawei, ["huawei.com"]),
  simpleBrand(siCisco, ["cisco.com"]),
  simpleBrand(siSap, ["sap.com"]),
  simpleBrand(siAnthropic, ["anthropic.com"]),
  simpleBrand(siProton, ["proton.me", "protonmail.com"]),
  simpleBrand(siZoho, ["zoho.com"]),
  simpleBrand(siYoutube, ["youtube.com"]),
  simpleBrand(siTwitch, ["twitch.tv"]),
  simpleBrand(siTelegram, ["telegram.org"]),
  simpleBrand(siWhatsapp, ["whatsapp.com", "whatsapp.net"]),
  simpleBrand(siPinterest, ["pinterest.com"]),
  simpleBrand(siMedium, ["medium.com"]),
  simpleBrand(siPatreon, ["patreon.com"]),
  simpleBrand(siBluesky, ["bsky.app", "blueskyweb.xyz"]),
  simpleBrand(siMastodon, ["mastodon.social"]),
  simpleBrand(siLine, ["line.me"]),
  simpleBrand(siSinaweibo, ["weibo.com"]),
  simpleBrand(siDouban, ["douban.com"]),
  simpleBrand(siBilibili, ["bilibili.com"]),
  simpleBrand(siDji, ["dji.com"]),
  simpleBrand(siLenovo, ["lenovo.com"]),
  simpleBrand(siAutodesk, ["autodesk.com"]),
];
